import type { Metadata } from "next";
import { WlExtensionProvider } from "./WlExtensionContext";
import { Poppins } from "next/font/google";
import "./globals.css";
import { UserProvider } from "./UserContext";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} font-sans antialiased`}
        style={{ fontFamily: "var(--font-poppins), sans-serif" }}
      >
        <WlExtensionProvider>
          <UserProvider>{children}</UserProvider>
        </WlExtensionProvider>
      </body>
    </html>
  );
}
